source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '10.1'

target ‘Urbo_iOS’ do
    pod 'Firebase/Auth'
    pod 'Firebase/Core'
    pod 'Firebase/Messaging'
    pod 'GoogleMaps'
    pod 'GooglePlaces'
    pod 'GooglePlacePicker'
    pod 'Google/SignIn'
    pod 'Firebase/Auth'
    pod 'FBSDKLoginKit'
end 
